version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "03:00"
    cooldown:
      default-days: 7
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
    ignore:
      # We need to ignore argon2 versions above 0.44.0 because the ordering of parameters in the hash have changed
      #  which will probably break a LOT of stuff
      - dependency-name: "argon2"
        versions: [ ">0.44.0" ]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "03:00"
    cooldown:
      default-days: 7
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
    cooldown:
      default-days: 7
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU