services:
  simulator:
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIRECT_URLS: "http://localhost:3001/callback"
      CLAIMS: "https://vocab.account.gov.uk/v1/coreIdentityJWT,https://vocab.account.gov.uk/v1/address,https://vocab.account.gov.uk/v1/passport"
    restart: on-failure
    network_mode: host
  selenium:
    platform: linux/x86_64/v8
    image: selenium/standalone-chrome:latest
    network_mode: host
  micro-rp:
    build:
      context: ./tests/acceptance/micro-rp
      dockerfile: Dockerfile
    restart: on-failure
    network_mode: host