services:
  simulator:
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIRECT_URLS: "http://localhost:3001/callback"
      CLAIMS: "https://vocab.account.gov.uk/v1/coreIdentityJWT,https://vocab.account.gov.uk/v1/address,https://vocab.account.gov.uk/v1/passport"
    restart: on-failure
    network_mode: host
  selenium:
    image: ${SELENIUM_IMAGE:-selenium/standalone-chrome:latest}
    network_mode: host
  micro-rp:
    build:
      context: ./tests/acceptance/micro-rp
      dockerfile: Dockerfile
    environment:
      - RP_CLIENT_ID=${RP_CLIENT_ID}
      - ENVIRONMENT=${ENVIRONMENT}
      - RP_PRIVATE_KEY=${RP_PRIVATE_KEY}
    restart: on-failure
    network_mode: host