version: "3.8"

services:
  simulator:
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    network_mode: host